name: Check Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Set up Python
        uses: eifinger/setup-rye@v4
        with:
          version: "latest"
          enable-cache: true
          cache-prefix: "${{ runner.os }}-rye-build"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: |
          rye sync
      - name: Build Package
        run: |
          rye build
      - name: Check package
        run: |
          rye run twine check --strict dist/*.whl
